M48
; DRILL file {KiCad 9.0.0} date 2025-03-31T20:00:44-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-03-31T20:00:44-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.700
%
G90
G05
T1
X129.49Y-123.558
T2
X85.388Y-99.64
X85.388Y-147.64
X118.388Y-99.64
X118.388Y-147.64
M30
